DROP TABLE ORDERS;
DROP TABLE ROOMS;
DROP TABLE ROOM_TYPES;
DROP TABLE CLIENTS;
DROP TABLE STAFF;
DROP TABLE HOTELS;

DROP SEQUENCE CLIENTS_SEQ;
DROP SEQUENCE ROOM_TYPES_SEQ;
DROP SEQUENCE ROOMS_SEQ;
DROP SEQUENCE ORDERS_SEQ;
DROP SEQUENCE STAFF_SEQ;
DROP SEQUENCE HOTELS_SEQ;

CREATE SEQUENCE CLIENTS_SEQ;
CREATE SEQUENCE ROOM_TYPES_SEQ;
CREATE SEQUENCE ROOMS_SEQ;
CREATE SEQUENCE ORDERS_SEQ;
CREATE SEQUENCE STAFF_SEQ;
CREATE SEQUENCE HOTELS_SEQ;

CREATE TABLE CLIENTS (
  ID NUMBER,
  FIRST_NAME VARCHAR2(50 CHAR),
  SECOND_NAME VARCHAR2(50 CHAR),
  FATHER_NAME VARCHAR2(50 CHAR),
  EMAIL VARCHAR2(50 CHAR),
  PHONE_NUMBER VARCHAR2(50 CHAR),
  HASH_PASSWORD VARCHAR2(100 CHAR),
  CONSTRAINT CLIENTS_PK PRIMARY KEY (ID)
);

CREATE TABLE ROOM_TYPES (
  ID NUMBER,
  HOTEL_ID NUMBER,
  TYPE_NAME VARCHAR2(100 CHAR),
  DESCRIPTION VARCHAR2(500 CHAR),
  COST DECIMAL,
  PATH_TO_PHOTO VARCHAR2(256 CHAR),
  CONSTRAINT ROOMTYPES_PK PRIMARY KEY (ID)
);

CREATE TABLE ROOMS (
  ID NUMBER,
  ROOM_NUMBER NUMBER,
  HOTEL_ID NUMBER,
  ROOM_TYPE_ID NUMBER,
  STATUS VARCHAR2(100),
  CONSTRAINT ROOMS_PK PRIMARY KEY (ID)
);

CREATE TABLE ORDERS (
  ID NUMBER,
  CLIENT_ID NUMBER,
  HOTEL_ID NUMBER,
  ROOM_ID NUMBER,
  START_DATE DATE,
  FINISH_DATE DATE,
  STATUS VARCHAR2(20 CHAR),
  CONSTRAINT ORDERS_PK PRIMARY KEY (ID)
);

CREATE TABLE STAFF (
  ID NUMBER,
  LOGIN VARCHAR2(50 CHAR),
  HASH_PASSWORD VARCHAR2(100 CHAR),
  EMAIL VARCHAR2(50 CHAR),
  HOTEL_ID NUMBER,
  TYPE VARCHAR2(50 CHAR),
  CONSTRAINT STAFF_PK PRIMARY KEY (ID)
);



CREATE TABLE HOTELS (
  ID NUMBER,
  NAME VARCHAR2(200 CHAR),
  DESCRIPTION VARCHAR2(400 CHAR),
  PHONE_NUMBER VARCHAR2(50 CHAR),
  ADDRESS VARCHAR2(200 CHAR),
  EMAIL VARCHAR2(50 CHAR),
  CONSTRAINT HOTELS_PK PRIMARY KEY (ID)
);


ALTER TABLE ROOM_TYPES ADD CONSTRAINT ROOMTYPES_FK0 FOREIGN KEY (HOTEL_ID) REFERENCES HOTELS(ID);

ALTER TABLE ROOMS ADD CONSTRAINT ROOMS_FK0 FOREIGN KEY (HOTEL_ID) REFERENCES HOTELS(ID);
ALTER TABLE ROOMS ADD CONSTRAINT ROOMS_FK1 FOREIGN KEY (ROOM_TYPE_ID) REFERENCES ROOM_TYPES(ID);

ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_FK0 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(ID);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_FK1 FOREIGN KEY (HOTEL_ID) REFERENCES HOTELS(ID);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_FK2 FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ID);

ALTER TABLE STAFF ADD CONSTRAINT STAFF_FK0 FOREIGN KEY (HOTEL_ID) REFERENCES HOTELS(ID);